---
title: "Pcap Stats Visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("scales")
library("patchwork")
```


Load the data...

```{r}
#file_name <- "data/test.csv"
file_name <- "MAWI20210707.csv"
d <- read_csv(file_name) %>%
  pivot_wider(names_from = "stat", values_from = "value")
```

Double check sanity of epoch duration...
```{r}
range(d$time[-1] - d$time[-nrow(d)])
```

Look at packet, byte, and flow counts per epoch --- the most basic summary...
```{r, fig.width=4, fig.height=4}
p1 <- d %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = totalPkts)) +
  scale_y_continuous(labels = label_number_si()) +
  labs(x = "", y = "pkts")
p2 <- d %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = totalBytes)) +
  scale_y_continuous(labels = label_number_si()) +
  labs(x = "", y = "bytes")
p3 <- d %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = numFlows)) +
  scale_y_continuous(labels = label_number_si()) +
  labs(x = "time (epochs)", y = "flows")
p1 / p2 / p3
```

Look at quantiles over time...
```{r, fig.width=4, fig.height=4}
target_qs <- c("005", "050", "095", "100")
p1 <- d %>%
  pivot_longer(cols = paste("q", target_qs, "pkts", sep=""), names_to = "key", values_to = "val") %>%
  select(time, key, val) %>%
  mutate(key = str_sub(key, 2, 4)) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = val, color = key)) +
  scale_y_continuous(trans="log10", labels = label_number_si()) +
  labs(x = "", y = "pkts", color = "quantile")

p2 <- d %>%
  pivot_longer(cols = paste("q", target_qs, "bytes", sep=""), names_to = "key", values_to = "val") %>%
  select(time, key, val) %>%
  mutate(key = str_sub(key, 2, 4)) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = val, color = key)) +
  scale_y_continuous(trans="log10", labels = label_number_si()) +
  labs(x = "time (epochs)", y = "bytes", color = "quantile")

(p1 / p2) + plot_layout(guides = "collect") & theme(legend.position = "top")
```

Can also visualize the distribution over all epochs...
```{r, fig.width=4, fig.height=4}
all_qs <- c(
  "000",
  "005",
  "010",
  "015",
  "020",
  "025",
  "030",
  "035",
  "040",
  "045",
  "050",
  "055",
  "060",
  "065",
  "070",
  "075",
  "080",
  "085",
  "090",
  "095",
  "100"
)
p1 <- d %>%
  pivot_longer(cols = paste("q", all_qs, "pkts", sep=""), names_to = "key", values_to = "val") %>%
  mutate(key = str_sub(key, 2, 4) %>% as.numeric()) %>%
  ggplot() +
  geom_violin(aes(x = val, y = key, group = key)) +
  scale_x_continuous(trans = "log10", labels = label_number_si()) +
  labs(x = "Packets", y = "CDF")
p2 <- d %>%
  pivot_longer(cols = paste("q", all_qs, "bytes", sep=""), names_to = "key", values_to = "val") %>%
  mutate(key = str_sub(key, 2, 4) %>% as.numeric()) %>%
  ggplot() +
  geom_violin(aes(x = val, y = key, group = key)) +
  scale_x_continuous(trans = "log10", labels = label_number_si()) +
  labs(x = "Bytes", y = "CDF")
p1 / p2
```

Look at different churns...
```{r, fig.width=4, fig.height=5}
# Note that we drop the first row cause the first churn is undefined (no previous observation)
p0 <- d %>%
  slice_tail(n = -1) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = churnTop0.1Percent)) +
  labs(x = "", y = "0.1%")
p1 <- d %>%
  slice_tail(n = -1) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = churnTop1Percent)) +
  labs(x = "", y = "1%")
p2 <- d %>%
  slice_tail(n = -1) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = churnTop5Percent)) +
  labs(x = "", y = "5%")
p3 <- d %>%
  slice_tail(n = -1) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = churnTop10Percent)) +
  labs(x = "", y = "10%")
p4 <- d %>%
  slice_tail(n = -1) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = churnGlobal)) +
  labs(x = "time (epochs)", y = "100%")
p0 / p1 / p2 / p3 / p4
```

And their corresponding quantiles...
```{r, fig.width=4, fig.height=5}
# Note that we drop the first row cause the first churn is undefined (no previous observation)
p0 <- d %>%
  slice_tail(n = -1) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = q0999pkts)) +
  labs(x = "", y = "0.1%")
p1 <- d %>%
  slice_tail(n = -1) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = q099pkts)) +
  labs(x = "", y = "1%")
p2 <- d %>%
  slice_tail(n = -1) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = q095pkts)) +
  labs(x = "", y = "5%")
p3 <- d %>%
  slice_tail(n = -1) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = q090pkts)) +
  labs(x = "", y = "10%")
p4 <- d %>%
  slice_tail(n = -1) %>%
  ggplot() +
  geom_line(aes(x = time - time[1], y = q000pkts)) +
  labs(x = "time (epochs)", y = "100%")
p0 / p1 / p2 / p3 / p4
```


